## Append samples you want in your CSV to this file as resources ##
resources:
- cache/infinispan/minimal.yaml.yaml
- cacheregion/engytita_v1alpha1_cacheregion.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
